apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    project: practice
    author: Xondamir
  name: nginx2
  namespace: x-umarov
spec:
  containers:
  - args:
    image: nginx
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
